name: RobVandermark
favicon: null
layout_spectrum: 0.52251
typography_spectrum: 0.62083
title: Rob Vandermark
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#4488e9'
    - '#bacae3'
    - '#5a5f43'
    - '#c76734'
  brandStrength: 0.9375
  lightness: 0.125
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
